{
    ["actionbar"] = {
        ["bar1"] = {
            ["buttonSize"] = 50,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["paging"] = {
                ["ROGUE"] = "",
            },
            ["point"] = "TOPLEFT",
        },
        ["bar10"] = {
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
        },
        ["bar2"] = {
            ["buttonsPerRow"] = 1,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["enabled"] = true,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar3"] = {
            ["backdropSpacing"] = 1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 1,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 33,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 2,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "",
        },
        ["bar5"] = {
            ["buttonSize"] = 50,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar6"] = {
            ["buttonSize"] = 33,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 2,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["enabled"] = true,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar7"] = {
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
        },
        ["bar8"] = {
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
        },
        ["bar9"] = {
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextYOffset"] = 3,
            ["macrotext"] = true,
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["countFont"] = "Futurapress",
            ["countFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
        },
        ["chargeCooldown"] = true,
        ["countTextXOffset"] = 4,
        ["countTextYOffset"] = 0,
        ["desaturateOnCooldown"] = true,
        ["equippedItem"] = true,
        ["extraActionButton"] = {
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
        },
        ["font"] = "Futurapress",
        ["fontOutline"] = "MONOCHROMETHICKOUTLINE",
        ["fontSize"] = 14,
        ["globalFadeAlpha"] = 1,
        ["hideCooldownBling"] = true,
        ["hotkeyTextPosition"] = "TOPLEFT",
        ["macroTextPosition"] = "BOTTOMLEFT",
        ["stanceBar"] = {
            ["buttonSize"] = 40,
            ["buttonsPerRow"] = 1,
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
        },
        ["transparent"] = true,
        ["vehicleExitButton"] = {
            ["hotkeyFont"] = "Futurapress",
            ["hotkeyFontOutline"] = "MONOCHROMETHICKOUTLINE",
            ["hotkeyFontSize"] = 14,
            ["hotkeyTextXOffset"] = 3,
            ["hotkeyTextYOffset"] = -6,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["size"] = 40,
        },
        ["debuffs"] = {
            ["size"] = 40,
        },
    },
    ["bags"] = {
        ["bagSize"] = 42,
        ["bagWidth"] = 474,
        ["bankSize"] = 42,
        ["bankWidth"] = 474,
        ["itemLevelCustomColorEnable"] = true,
        ["junkDesaturate"] = true,
        ["scrapIcon"] = true,
        ["showBindType"] = true,
        ["vendorGrays"] = {
            ["enable"] = true,
        },
    },
    ["chat"] = {
        ["panelHeight"] = 236,
        ["panelWidth"] = 472,
        ["tabFontSize"] = 10,
    },
    ["convertPages"] = true,
    ["databars"] = {
        ["experience"] = {
            ["orientation"] = "HORIZONTAL",
            ["width"] = 778,
        },
        ["reputation"] = {
            ["enable"] = true,
            ["width"] = 778,
        },
    },
    ["datatexts"] = {
        ["panels"] = {
            ["Darth_Panel_1"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                [4] = "",
                [5] = "",
                [6] = "",
                [7] = "",
                [8] = "",
                ["enable"] = false,
            },
            ["LeftChatDataPanel"] = {
                [3] = "Time Played",
            },
        },
    },
    ["general"] = {
        ["bonusObjectivePosition"] = "AUTO",
        ["bottomPanel"] = false,
        ["minimap"] = {
            ["size"] = 220,
        },
        ["objectiveFrameHeight"] = 400,
        ["talkingHeadFrameScale"] = 1,
        ["totems"] = {
            ["spacing"] = 8,
        },
        ["valuecolor"] = {
            ["b"] = 0.58823400735855,
            ["g"] = 0.99999779462814,
            ["r"] = 0,
        },
    },
    ["movers"] = {
        ["AlertFrameMover"] = "TOP,ElvUIParent,TOP,-1,-18",
        ["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,-1,-36",
        ["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-118,-471",
        ["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274",
        ["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274",
        ["BossButton"] = "TOP,ElvUIParent,TOP,-200,-614",
        ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-118,-406",
        ["BuffsMover"] = "TOPRIGHT,MMHolder,TOPLEFT,-7,-1",
        ["DebuffsMover"] = "BOTTOMRIGHT,MMHolder,BOTTOMLEFT,-7,1",
        ["DurabilityFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-135,-300",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,102",
        ["ElvAB_2"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-38,-438",
        ["ElvAB_3"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-438",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,-186,0",
        ["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,-1",
        ["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,186,0",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-248",
        ["ElvUF_FocusCastbarMover"] = "TOPLEFT,ElvUF_Focus,BOTTOMLEFT,0,-1",
        ["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,256",
        ["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,269",
        ["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,600,19",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,204",
        ["ElvUF_PlayerMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,601,208",
        ["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,269",
        ["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,114,345",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-186",
        ["ElvUF_TargetCastbarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-600,187",
        ["ElvUF_TargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-600,208",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-600,19",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,RightChatPanel,BOTTOMRIGHT,0,26",
        ["ElvUIBankMover"] = "BOTTOMLEFT,LeftChatPanel,BOTTOMLEFT,0,26",
        ["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-5",
        ["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-255",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,4",
        ["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,-1,-120",
        ["LootFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-104",
        ["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,-1,507",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-3",
        ["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96",
        ["MirrorTimer2Mover"] = "TOP,MirrorTimer1,BOTTOM,0,0",
        ["MirrorTimer3Mover"] = "TOP,MirrorTimer2,BOTTOM,0,0",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325",
        ["PetAB"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-71,-470",
        ["RaidMarkerBarAnchor"] = "TOPLEFT,ElvUIParent,TOPLEFT,502,-627",
        ["RaidUtility_Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,571,-4",
        ["ReputationBarMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,4",
        ["ShiftAB"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,479,4",
        ["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
        ["SquareMinimapButtonBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,265",
        ["TalkingHeadFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-404,-545",
        ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,265",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-30",
        ["TotemBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,521,5",
        ["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-82",
        ["VehicleLeaveButton"] = "TOP,ElvUIParent,TOP,-261,-624",
        ["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4",
        ["ZoneAbility"] = "TOP,ElvUIParent,TOP,-318,-614",
    },
    ["tooltip"] = {
        ["healthBar"] = {
            ["fontOutline"] = "MONOCHROMEOUTLINE",
            ["height"] = 12,
        },
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.58823400735855,
                ["g"] = 0.99999779462814,
                ["r"] = 0,
            },
            ["castClassColor"] = true,
            ["healthclass"] = true,
        },
        ["font"] = "PT Sans Narrow",
        ["fontOutline"] = "NONE",
        ["fontSize"] = 16,
        ["smoothbars"] = true,
        ["units"] = {
            ["boss"] = {
                ["buffs"] = {
                    ["maxDuration"] = 300,
                    ["sizeOverride"] = 27,
                    ["yOffset"] = 16,
                },
                ["castbar"] = {
                    ["width"] = 246,
                },
                ["debuffs"] = {
                    ["maxDuration"] = 300,
                    ["sizeOverride"] = 27,
                    ["yOffset"] = -16,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["height"] = 17,
                },
                ["width"] = 246,
            },
            ["focus"] = {
                ["castbar"] = {
                    ["width"] = 270,
                },
                ["width"] = 270,
            },
            ["pet"] = {
                ["castbar"] = {
                    ["iconSize"] = 32,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["enable"] = true,
                },
                ["disableTargetGlow"] = false,
                ["infoPanel"] = {
                    ["height"] = 14,
                },
                ["width"] = 270,
            },
            ["player"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["attachTo"] = "FRAME",
                    ["enable"] = true,
                },
                ["castbar"] = {
                    ["customTimeFont"] = {
                        ["fontSize"] = 16,
                    },
                    ["displayTarget"] = true,
                    ["height"] = 31,
                    ["insideInfoPanel"] = false,
                    ["spark"] = false,
                    ["width"] = 438,
                },
                ["classbar"] = {
                    ["height"] = 16,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["attachTo"] = "BUFFS",
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["position"] = "RIGHT",
                    ["xOffset"] = -2,
                },
                ["height"] = 82,
                ["name"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["text_format"] = "[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]",
                },
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["height"] = 16,
                    ["position"] = "LEFT",
                    ["text_format"] = "[powercolor][power:current]",
                    ["xOffset"] = 2,
                },
            },
            ["raid1"] = {
                ["growthDirection"] = "RIGHT_UP",
                ["infoPanel"] = {
                    ["enable"] = true,
                },
                ["name"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "[namecolor][name:medium]",
                    ["xOffset"] = 2,
                },
                ["numGroups"] = 8,
                ["rdebuffs"] = {
                    ["size"] = 30,
                    ["xOffset"] = 30,
                    ["yOffset"] = 25,
                },
                ["resurrectIcon"] = {
                    ["attachTo"] = "BOTTOMRIGHT",
                },
                ["roleIcon"] = {
                    ["attachTo"] = "InfoPanel",
                    ["size"] = 12,
                    ["xOffset"] = 0,
                },
                ["width"] = 92,
            },
            ["raid3"] = {
                ["growthDirection"] = "RIGHT_UP",
                ["height"] = 44,
                ["infoPanel"] = {
                    ["enable"] = true,
                },
                ["name"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["position"] = "BOTTOMLEFT",
                    ["xOffset"] = 2,
                },
                ["power"] = {
                    ["enable"] = true,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["size"] = 30,
                    ["xOffset"] = 30,
                    ["yOffset"] = 25,
                },
                ["resurrectIcon"] = {
                    ["attachTo"] = "BOTTOMRIGHT",
                },
                ["roleIcon"] = {
                    ["attachTo"] = "InfoPanel",
                    ["enable"] = true,
                    ["size"] = 12,
                    ["xOffset"] = 0,
                },
                ["width"] = 92,
            },
            ["target"] = {
                ["castbar"] = {
                    ["height"] = 20,
                    ["insideInfoPanel"] = false,
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                },
                ["height"] = 82,
                ["name"] = {
                    ["attachTextTo"] = "InfoPanel",
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["height"] = 16,
                },
            },
            ["targettarget"] = {
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["enable"] = false,
                },
                ["disableMouseoverGlow"] = true,
                ["power"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["enable"] = false,
                    ["xOffset"] = 2,
                    ["yOffset"] = 0,
                },
                ["threatStyle"] = "GLOW",
                ["width"] = 270,
            },
        },
    },
}::profile::DPS/Tank v3