{
    ["actionbar"] = {
        ["bar1"] = {
            ["buttonSize"] = 40,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
        },
        ["bar10"] = {
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
        },
        ["bar2"] = {
            ["buttonSize"] = 40,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["enabled"] = true,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar3"] = {
            ["buttonSize"] = 27,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 4,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 27,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 4,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar5"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 4,
            ["buttons"] = 12,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["inheritGlobalFade"] = true,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["showGrid"] = false,
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar6"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 4,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["enabled"] = true,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["inheritGlobalFade"] = true,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["showGrid"] = false,
            ["visibility"] = "[petbattle] hide; show",
        },
        ["bar7"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 4,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["enabled"] = true,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["inheritGlobalFade"] = true,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
            ["point"] = "TOPLEFT",
            ["showGrid"] = false,
        },
        ["bar8"] = {
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
        },
        ["bar9"] = {
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
            ["macroFont"] = "PT Sans Narrow",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 14,
            ["macroTextPosition"] = "BOTTOMLEFT",
            ["macroTextXOffset"] = -2,
            ["macroTextYOffset"] = 1,
            ["macrotext"] = true,
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 40,
            ["buttonsPerRow"] = 10,
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
        },
        ["desaturateOnCooldown"] = true,
        ["extraActionButton"] = {
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
        },
        ["font"] = "PT Sans Narrow",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 14,
        ["macroTextPosition"] = "BOTTOMLEFT",
        ["rightClickSelfCast"] = true,
        ["stanceBar"] = {
            ["buttons"] = 8,
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
        },
        ["transparent"] = true,
        ["vehicleExitButton"] = {
            ["hotkeyFont"] = "PT Sans Narrow",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 14,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["size"] = 40,
            ["timeFont"] = "PT Sans Narrow",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 12,
        },
        ["debuffs"] = {
            ["countFont"] = "PT Sans Narrow",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["size"] = 40,
            ["timeFont"] = "PT Sans Narrow",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 12,
        },
    },
    ["bags"] = {
        ["bagSize"] = 42,
        ["bagWidth"] = 474,
        ["bankSize"] = 42,
        ["bankWidth"] = 474,
        ["clearSearchOnClose"] = true,
        ["countFont"] = "PT Sans Narrow",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 12,
        ["currencyFormat"] = "ICON",
        ["itemInfoFont"] = "PT Sans Narrow",
        ["itemInfoFontOutline"] = "OUTLINE",
        ["itemLevelCustomColorEnable"] = true,
        ["itemLevelFont"] = "PT Sans Narrow",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 12,
        ["junkIcon"] = true,
        ["moneyCoins"] = false,
        ["moneyFormat"] = "BLIZZARD",
        ["scrapIcon"] = true,
        ["showBindType"] = true,
        ["split"] = {
            ["bag1"] = true,
            ["bag2"] = true,
            ["bag3"] = true,
            ["bag4"] = true,
            ["bagSpacing"] = 7,
            ["player"] = true,
        },
        ["useBlizzardCleanup"] = true,
        ["vendorGrays"] = {
            ["enable"] = true,
        },
    },
    ["chat"] = {
        ["copyChatLines"] = true,
        ["fadeChatToggles"] = false,
        ["fadeTabsNoBackdrop"] = false,
        ["fontSize"] = 12,
        ["historySize"] = 250,
        ["panelColor"] = {
            ["a"] = 0.30239480733871,
            ["b"] = 0.058823529411765,
            ["g"] = 0.058823529411765,
            ["r"] = 0.058823529411765,
        },
        ["panelHeight"] = 240,
        ["panelWidth"] = 500,
        ["tabSelectorColor"] = {
            ["b"] = 0.92156660556793,
            ["g"] = 0.78039044141769,
            ["r"] = 0.24705828726292,
        },
        ["timeStampFormat"] = "%I:%M ",
        ["timeStampLocalTime"] = true,
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["checkSeconds"] = true,
        ["mmssThreshold"] = 600,
    },
    ["databars"] = {
        ["azerite"] = {
            ["enable"] = false,
        },
        ["experience"] = {
            ["width"] = 600,
        },
        ["reputation"] = {
            ["enable"] = true,
        },
        ["threat"] = {
            ["height"] = 24,
            ["width"] = 472,
        },
    },
    ["datatexts"] = {
        ["panels"] = {
            ["Darth_Panel_1"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                [4] = "",
                [5] = "",
                [6] = "",
                [7] = "",
                [8] = "",
                ["enable"] = false,
            },
            ["LeftChatDataPanel"] = {
                [3] = "Time Played",
            },
        },
    },
    ["general"] = {
        ["autoRepair"] = "GUILD",
        ["autoTrackReputation"] = true,
        ["bonusObjectivePosition"] = "AUTO",
        ["fontStyle"] = "NONE",
        ["minimap"] = {
            ["size"] = 220,
        },
        ["objectiveFrameAutoHideInKeystone"] = true,
        ["objectiveFrameHeight"] = 800,
        ["talkingHeadFrameScale"] = 1,
        ["totems"] = {
            ["growthDirection"] = "HORIZONTAL",
            ["size"] = 50,
            ["spacing"] = 8,
        },
        ["valuecolor"] = {
            ["b"] = 0.92156660556793,
            ["g"] = 0.78039044141769,
            ["r"] = 0.24705828726292,
        },
    },
    ["layoutSetting"] = "dpsCaster",
    ["movers"] = {
        ["AlertFrameMover"] = "TOP,ElvUIParent,TOP,-1,-18",
        ["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,-1,-36",
        ["ArenaHeaderMover"] = "BOTTOMRIGHT,ElvUIParent,RIGHT,-105,-164",
        ["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-244",
        ["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274",
        ["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274",
        ["BigButtonsFarmBar"] = "TOP,UIParent,TOP,0,-250",
        ["BigButtonsSeedBarMover"] = "TOP,UIParent,TOP,0,-300",
        ["BossButton"] = "TOP,ElvUIParent,TOP,-159,-614",
        ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-381,-298",
        ["BuffsMover"] = "TOPRIGHT,MMHolder,TOPLEFT,-7,0",
        ["DTPanelDarth_Panel_1Mover"] = "CENTER,ElvUIParent,CENTER,0,0",
        ["DebuffsMover"] = "BOTTOMRIGHT,MMHolder,BOTTOMLEFT,-7,0",
        ["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,-125,174",
        ["ElvAB_10"] = "BOTTOM,ElvUI_Bar1,TOP,0,202",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,126,174",
        ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,-305,174",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,306,174",
        ["ElvAB_5"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,507,184",
        ["ElvAB_6"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,507,96",
        ["ElvAB_7"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,507,8",
        ["ElvAB_8"] = "BOTTOM,ElvUI_Bar1,TOP,0,122",
        ["ElvAB_9"] = "BOTTOM,ElvUI_Bar1,TOP,0,162",
        ["ElvNP_PlayerMover"] = "TOP,UIParent,CENTER,0,-149",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-248",
        ["ElvUF_FocusCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,323",
        ["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,288,347",
        ["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,543,300",
        ["ElvUF_PetCastbarMover"] = "TOPLEFT,ElvUF_Pet,BOTTOMLEFT,0,-1",
        ["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,809,263",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,1,256",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-550,300",
        ["ElvUF_Raid1Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,448,300",
        ["ElvUF_Raid3Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,448,300",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-186",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,342",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,550,300",
        ["ElvUF_TargetTargetMover"] = "BOTTOM,UIParent,BOTTOM,550,263",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,RightChatPanel,BOTTOMRIGHT,0,26",
        ["ElvUIBankMover"] = "BOTTOMLEFT,LeftChatPanel,BOTTOMLEFT,0,26",
        ["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,250,-4",
        ["HonorBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-251",
        ["LeftChatMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,4,4",
        ["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,-1,-120",
        ["LootFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,418,-186",
        ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-591",
        ["MicrobarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,0",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-3",
        ["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96",
        ["MirrorTimer2Mover"] = "TOP,MirrorTimer1,BOTTOM,0,0",
        ["MirrorTimer3Mover"] = "TOP,MirrorTimer2,BOTTOM,0,0",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325",
        ["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,1,132",
        ["PetBattleABMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,4",
        ["PetBattleStatusMover"] = "TOP,PetBattleFrame,TOP,0,0",
        ["RaidMarkerBarAnchor"] = "TOPLEFT,ElvUIParent,TOPLEFT,505,-627",
        ["RaidUtility_Mover"] = "TOP,ElvUIParent,TOP,-399,1",
        ["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-243",
        ["RightChatMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,4",
        ["SLEGhostFrameMover"] = "TOP,ElvUIParent,TOP,0,-149",
        ["SLE_BG_1_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,0,21",
        ["SLE_BG_2_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOM,-337,21",
        ["SLE_BG_3_Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOM,337,21",
        ["SLE_BG_4_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,0,249",
        ["SLE_FarmPortalMover"] = "BOTTOMLEFT,SLE_ToolsToolbarsAnchor,TOPLEFT,0,1",
        ["SLE_FarmSeedMover"] = "LEFT,ElvUIParent,LEFT,24,-160",
        ["SLE_FarmToolMover"] = "BOTTOMLEFT,SLE_SeedToolbarsAnchor,TOPLEFT,0,1",
        ["SLE_GarrisonToolMover"] = "LEFT,ElvUIParent,LEFT,23,0",
        ["SLE_Location_Mover"] = "TOP,ElvUIParent,TOP,0,-22",
        ["SLE_UIButtonsMover"] = "LEFT,ElvUIParent,LEFT,-2,0",
        ["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,100",
        ["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
        ["TalkingHeadFrameMover"] = "TOP,UIParent,TOP,403,-272",
        ["ThreatBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,45",
        ["TooltipMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,247",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-29",
        ["TotemBarMover"] = "BOTTOM,UIParent,BOTTOM,-459,81",
        ["UIErrorsFrameMover"] = "TOP,UIParent,TOP,0,-122",
        ["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,367,-210",
        ["VehicleLeaveButton"] = "TOP,ElvUIParent,TOP,-263,-624",
        ["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4",
        ["ZoneAbility"] = "TOP,ElvUIParent,TOP,-214,-614",
    },
    ["nameplates"] = {
        ["colors"] = {
            ["reactions"] = {
                ["good"] = {
                    ["b"] = 0.29,
                    ["g"] = 0.67,
                    ["r"] = 0.3,
                },
                ["neutral"] = {
                    ["g"] = 0.76,
                },
            },
            ["selection"] = {
                [0] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                [2] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
                [3] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
            },
            ["threat"] = {
                ["badColor"] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                ["goodColor"] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
                ["goodTransition"] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
            },
        },
        ["units"] = {
            ["ENEMY_PLAYER"] = {
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
                ["portrait"] = {
                    ["classicon"] = false,
                    ["enable"] = true,
                    ["position"] = "LEFT",
                    ["xOffset"] = 0,
                    ["yOffset"] = 0,
                },
            },
        },
    },
    ["tooltip"] = {
        ["alwaysShowRealm"] = true,
        ["cursorAnchorType"] = "ANCHOR_CURSOR_RIGHT",
        ["cursorAnchorX"] = 18,
        ["cursorAnchorY"] = 18,
        ["healthBar"] = {
            ["font"] = "PT Sans Narrow",
            ["fontOutline"] = "NONE",
            ["fontSize"] = 12,
            ["height"] = 12,
        },
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.8,
                ["g"] = 0.8,
                ["r"] = 0.8,
            },
            ["castClassColor"] = true,
            ["castColor"] = {
                ["b"] = 0.30980392156863,
                ["g"] = 0.30980392156863,
                ["r"] = 0.30980392156863,
            },
            ["castInterruptedColor"] = {
                ["b"] = 0.30196078431373,
                ["g"] = 0.30196078431373,
                ["r"] = 0.30196078431373,
            },
            ["castNoInterrupt"] = {
                ["b"] = 0.25098039215686,
                ["g"] = 0.25098039215686,
                ["r"] = 0.78039215686275,
            },
            ["debuffHighlight"] = {
                ["Magic"] = {
                    ["a"] = 0.44999998807907,
                },
            },
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["class"] = true,
                    ["enable"] = false,
                },
            },
            ["health"] = {
                ["b"] = 0.058823529411765,
                ["g"] = 0.058823529411765,
                ["r"] = 0.058823529411765,
            },
            ["health_backdrop"] = {
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 1,
            },
            ["health_backdrop_dead"] = {
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0.11764705882353,
            },
            ["healthclass"] = true,
            ["tapped"] = {
                ["b"] = 0.015686274509804,
                ["g"] = 0,
                ["r"] = 1,
            },
        },
        ["font"] = "PT Sans Narrow",
        ["fontOutline"] = "NONE",
        ["fontSize"] = 16,
        ["smoothbars"] = true,
        ["units"] = {
            ["boss"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["maxDuration"] = 300,
                    ["sizeOverride"] = 27,
                    ["xOffset"] = -27,
                    ["yOffset"] = -27,
                },
                ["castbar"] = {
                    ["width"] = 250,
                },
                ["customTexts"] = {
                    ["health %"] = {
                        ["attachTextTo"] = "InfoPanel",
                        ["enable"] = true,
                        ["font"] = "PT Sans Narrow",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[healthcolor][health:percent]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                    ["power %"] = {
                        ["attachTextTo"] = "InfoPanel",
                        ["enable"] = true,
                        ["font"] = "PT Sans Narrow",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 16,
                        ["text_format"] = "[powercolor][power:percent]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "BUFFS",
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["maxDuration"] = 300,
                    ["sizeOverride"] = 27,
                    ["yOffset"] = 0,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["enable"] = true,
                    ["height"] = 17,
                },
                ["spacing"] = 10,
                ["width"] = 250,
            },
            ["focus"] = {
                ["castbar"] = {
                    ["width"] = 250,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["sizeOverride"] = 36,
                },
                ["width"] = 250,
            },
            ["party"] = {
                ["customTexts"] = {
                    ["Small Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "PT Sans Narrow",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "",
                        ["xOffset"] = 0,
                        ["yOffset"] = -16,
                    },
                },
                ["debuffs"] = {
                    ["numrows"] = 2,
                    ["perrow"] = 3,
                    ["sizeOverride"] = 27,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["showPlayer"] = false,
            },
            ["pet"] = {
                ["castbar"] = {
                    ["iconSize"] = 32,
                },
                ["debuffs"] = {
                    ["enable"] = true,
                },
                ["disableTargetGlow"] = false,
                ["infoPanel"] = {
                    ["height"] = 14,
                },
                ["width"] = 270,
            },
            ["player"] = {
                ["castbar"] = {
                    ["displayTarget"] = true,
                    ["height"] = 30,
                    ["insideInfoPanel"] = false,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 503,
                },
                ["classbar"] = {
                    ["height"] = 14,
                },
                ["disableMouseoverGlow"] = true,
                ["healPrediction"] = {
                    ["absorbStyle"] = "NORMAL",
                },
                ["height"] = 82,
                ["name"] = {
                    ["text_format"] = "[namecolor][name]",
                },
                ["power"] = {
                    ["height"] = 16,
                    ["powerPrediction"] = true,
                },
            },
            ["raid1"] = {
                ["customTexts"] = {
                    ["Small Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "PT Sans Narrow",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[namecolor][name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -13,
                    },
                },
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "RIGHT",
                },
                ["horizontalSpacing"] = 2,
                ["infoPanel"] = {
                    ["height"] = 6,
                },
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                },
                ["numGroups"] = 4,
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                },
                ["rdebuffs"] = {
                    ["size"] = 18,
                    ["yOffset"] = 23,
                },
                ["resurrectIcon"] = {
                    ["attachTo"] = "BOTTOMRIGHT",
                },
                ["roleIcon"] = {
                    ["damager"] = false,
                    ["position"] = "BOTTOMLEFT",
                    ["size"] = 16,
                    ["yOffset"] = 16,
                },
                ["verticalSpacing"] = 2,
                ["width"] = 71,
            },
            ["raid3"] = {
                ["customTexts"] = {
                    ["Small Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "PT Sans Narrow",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[namecolor][name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -13,
                    },
                },
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "RIGHT",
                },
                ["height"] = 44,
                ["horizontalSpacing"] = 2,
                ["infoPanel"] = {
                    ["height"] = 6,
                },
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["enable"] = true,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["size"] = 18,
                    ["yOffset"] = 23,
                },
                ["resurrectIcon"] = {
                    ["attachTo"] = "BOTTOMRIGHT",
                },
                ["roleIcon"] = {
                    ["damager"] = false,
                    ["enable"] = true,
                    ["position"] = "BOTTOMLEFT",
                    ["size"] = 16,
                    ["yOffset"] = 16,
                },
                ["verticalSpacing"] = 2,
                ["width"] = 71,
            },
            ["target"] = {
                ["castbar"] = {
                    ["height"] = 20,
                    ["insideInfoPanel"] = false,
                    ["width"] = 296,
                },
                ["disableMouseoverGlow"] = true,
                ["healPrediction"] = {
                    ["absorbStyle"] = "NORMAL",
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["xOffset"] = 2,
                },
                ["height"] = 82,
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["height"] = 16,
                    ["position"] = "RIGHT",
                    ["xOffset"] = -2,
                },
            },
            ["targettarget"] = {
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["enable"] = false,
                },
                ["disableMouseoverGlow"] = true,
                ["power"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["enable"] = false,
                    ["xOffset"] = 2,
                    ["yOffset"] = 0,
                },
                ["threatStyle"] = "GLOW",
                ["width"] = 270,
            },
        },
    },
}::profile::DPS/Tank v4.2